#!/usr/bin/env bash
# Render the Cilium Kind override patch with the resolved control-plane IP.
# This produces manifests/overrides/cilium-kind-apiserver.generated.yaml that
# is referenced from furyctl.yaml customPatches.
#
# Why: Cilium in kube-proxy-replacement needs KUBERNETES_SERVICE_HOST pointing
# to the API server IP, not the Service VIP. The IP is assigned by Docker at
# cluster boot time, so it cannot be hardcoded in a static customPatch.
#
# This script runs BEFORE `furyctl apply` so the generated file is on disk
# when furyctl reads customPatches.patches.
set -euo pipefail

CLUSTER_NAME="${CLUSTER_NAME:-fury-baobank}"
OUT="${1:-manifests/overrides/cilium-kind-apiserver.generated.yaml}"

CP_IP=$(docker inspect "${CLUSTER_NAME}-control-plane" \
  --format '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}')

if [[ -z "${CP_IP}" ]]; then
  echo "ERROR: failed to discover control-plane IP for ${CLUSTER_NAME}" >&2
  exit 1
fi

echo "==> Rendering ${OUT} with k8s-service-host=${CP_IP}"
mkdir -p "$(dirname "${OUT}")"
cat > "${OUT}" <<EOF
# GENERATED by scripts/render-cilium-override.sh — do not edit by hand.
# THIS IS A KIND-SPECIFIC WORKAROUND (see findings NETWORKING-001).
# The upstream-clean fix is to add kubeProxyReplacement support to the KFD
# networking module so the Distribution schema can carry k8sServiceHost.
#
# Why this workaround is needed:
#   - On Kind with kube-proxy disabled, Cilium cannot reach the Service VIP
#     (10.96.0.1) at boot — nobody programs the VIP before Cilium itself.
#   - Cilium's Go k8s client reads KUBERNETES_SERVICE_HOST from pod env.
#     This env var must point to the control-plane IP (dynamic per boot).
#
# Where it has to be set:
#   - cilium-agent (main container)
#   - config (init container — runs first, talks to the API)
#   - cilium-operator (a separate Deployment — also talks to the API early)
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cilium
  namespace: kube-system
spec:
  template:
    spec:
      initContainers:
        - name: config
          env:
            - name: KUBERNETES_SERVICE_HOST
              value: "${CP_IP}"
            - name: KUBERNETES_SERVICE_PORT
              value: "6443"
      containers:
        - name: cilium-agent
          env:
            - name: KUBERNETES_SERVICE_HOST
              value: "${CP_IP}"
            - name: KUBERNETES_SERVICE_PORT
              value: "6443"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cilium-operator
  namespace: kube-system
spec:
  template:
    spec:
      containers:
        - name: cilium-operator
          env:
            - name: KUBERNETES_SERVICE_HOST
              value: "${CP_IP}"
            - name: KUBERNETES_SERVICE_PORT
              value: "6443"
EOF
